import typing
from System import Attribute

class ValueSerializerAttribute(Attribute):
    @typing.overload
    def __init__(self, valueSerializerType: typing.Type[typing.Any]) -> None: ...
    @typing.overload
    def __init__(self, valueSerializerTypeName: str) -> None: ...
    @property
    def TypeId(self) -> typing.Any: ...
    @property
    def ValueSerializerType(self) -> typing.Type[typing.Any]: ...
    @property
    def ValueSerializerTypeName(self) -> str: ...

