# coding: utf-8

"""
    CNB OPENAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Contact: cnb@tencent.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from cnb_api.models.dto_dependency import DtoDependency
from cnb_api.models.dto_file import DtoFile
from cnb_api.models.dto_last_pusher import DtoLastPusher
from cnb_api.models.dto_npm_tag import DtoNpmTag
from typing import Optional, Set
from typing_extensions import Self

class DtoNpmTagDetail(BaseModel):
    """
    DtoNpmTagDetail
    """ # noqa: E501
    address: Optional[StrictStr] = None
    dependencies: Optional[List[DtoDependency]] = None
    desc: Optional[StrictStr] = None
    files: Optional[List[DtoFile]] = None
    last_pusher: Optional[DtoLastPusher] = None
    package: Optional[StrictStr] = None
    pull_count: Optional[StrictInt] = None
    recent_pull_count: Optional[StrictInt] = None
    size: Optional[StrictInt] = None
    slug: Optional[StrictStr] = None
    status: Optional[StrictStr] = None
    tag: Optional[StrictStr] = None
    tags: Optional[List[DtoNpmTag]] = None
    __properties: ClassVar[List[str]] = ["address", "dependencies", "desc", "files", "last_pusher", "package", "pull_count", "recent_pull_count", "size", "slug", "status", "tag", "tags"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DtoNpmTagDetail from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in dependencies (list)
        _items = []
        if self.dependencies:
            for _item_dependencies in self.dependencies:
                if _item_dependencies:
                    _items.append(_item_dependencies.to_dict())
            _dict['dependencies'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in files (list)
        _items = []
        if self.files:
            for _item_files in self.files:
                if _item_files:
                    _items.append(_item_files.to_dict())
            _dict['files'] = _items
        # override the default output from pydantic by calling `to_dict()` of last_pusher
        if self.last_pusher:
            _dict['last_pusher'] = self.last_pusher.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in tags (list)
        _items = []
        if self.tags:
            for _item_tags in self.tags:
                if _item_tags:
                    _items.append(_item_tags.to_dict())
            _dict['tags'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DtoNpmTagDetail from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "address": obj.get("address"),
            "dependencies": [DtoDependency.from_dict(_item) for _item in obj["dependencies"]] if obj.get("dependencies") is not None else None,
            "desc": obj.get("desc"),
            "files": [DtoFile.from_dict(_item) for _item in obj["files"]] if obj.get("files") is not None else None,
            "last_pusher": DtoLastPusher.from_dict(obj["last_pusher"]) if obj.get("last_pusher") is not None else None,
            "package": obj.get("package"),
            "pull_count": obj.get("pull_count"),
            "recent_pull_count": obj.get("recent_pull_count"),
            "size": obj.get("size"),
            "slug": obj.get("slug"),
            "status": obj.get("status"),
            "tag": obj.get("tag"),
            "tags": [DtoNpmTag.from_dict(_item) for _item in obj["tags"]] if obj.get("tags") is not None else None
        })
        return _obj


