# coding: utf-8

"""
    CNB OPENAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Contact: cnb@tencent.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict
from typing import Any, ClassVar, Dict, List, Optional
from cnb_api.models.dto_overwrite_policy import DtoOverwritePolicy
from cnb_api.models.dto_registry_clean_detail import DtoRegistryCleanDetail
from cnb_api.models.dto_version_policy import DtoVersionPolicy
from typing import Optional, Set
from typing_extensions import Self

class DtoRegistryPolicy(BaseModel):
    """
    DtoRegistryPolicy
    """ # noqa: E501
    clean_policy_detail: Optional[DtoRegistryCleanDetail] = None
    overwrite_policy: Optional[DtoOverwritePolicy] = None
    version_policy: Optional[DtoVersionPolicy] = None
    __properties: ClassVar[List[str]] = ["clean_policy_detail", "overwrite_policy", "version_policy"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DtoRegistryPolicy from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of clean_policy_detail
        if self.clean_policy_detail:
            _dict['clean_policy_detail'] = self.clean_policy_detail.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DtoRegistryPolicy from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "clean_policy_detail": DtoRegistryCleanDetail.from_dict(obj["clean_policy_detail"]) if obj.get("clean_policy_detail") is not None else None,
            "overwrite_policy": obj.get("overwrite_policy"),
            "version_policy": obj.get("version_policy")
        })
        return _obj


