
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-04-24T14:18:37-0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "5a6ec5645f426b24c13755893e0df66d7c2f94f3",
 "version": "2.60.1b0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
