import enum

__all__ = ['Auto_Mode', 'getProjectPath', 'getTempDir', 'is_nuitka_packaged', 'is_pyinstaller_packaged', 'print_file_tree', 'copy_file_to', 'isEntryPoint', 'get_real_exe_dir']

class Auto_Mode(enum.Enum):
    disable = 0
    normal = 1
    high = 2
    highest = 3

def isEntryPoint(): ...
def get_real_exe_dir() -> str: ...
def getTempDir(relative_path: str = ''): ...
def print_file_tree(path) -> None: ...
def is_nuitka_packaged() -> bool: ...
def is_pyinstaller_packaged() -> bool: ...
def copy_file_to(becopyed_file_path: str, new_file_path: str, cover: bool = False, file_name: str = None): ...
def getProjectPath(layer: int = 0, auto: Auto_Mode = ...) -> str: ...
