# Generated by Django 4.2.19 on 2025-03-28 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_ba', '0002_companyba'),
    ]

    operations = [
        migrations.AddField(
            model_name='companybankaccount',
            name='account_holder_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='companybankaccount',
            name='address',
            field=models.TextField(blank=True, default=''),
        ),
    ]
