# coding: utf-8

"""
    CNB OPENAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Contact: cnb@tencent.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cnb_api.models.api_commit_object import ApiCommitObject

class TestApiCommitObject(unittest.TestCase):
    """ApiCommitObject unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiCommitObject:
        """Test ApiCommitObject
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiCommitObject`
        """
        model = ApiCommitObject()
        if include_optional:
            return ApiCommitObject(
                author = cnb_api.models.api/signature.api.Signature(
                    date = '', 
                    email = '', 
                    name = '', ),
                comment_count = 56,
                committer = cnb_api.models.api/signature.api.Signature(
                    date = '', 
                    email = '', 
                    name = '', ),
                message = '',
                tree = cnb_api.models.api/commit_object_tree.api.CommitObjectTree(
                    sha = '', ),
                verification = cnb_api.models.api/commit_object_verification.api.CommitObjectVerification(
                    payload = '', 
                    resone = '', 
                    signature = '', 
                    verified = True, )
            )
        else:
            return ApiCommitObject(
        )
        """

    def testApiCommitObject(self):
        """Test ApiCommitObject"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
