# coding: utf-8

"""
    CNB OPENAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Contact: cnb@tencent.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cnb_api.models.dto_activity_join_group_detail import DtoActivityJoinGroupDetail

class TestDtoActivityJoinGroupDetail(unittest.TestCase):
    """DtoActivityJoinGroupDetail unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DtoActivityJoinGroupDetail:
        """Test DtoActivityJoinGroupDetail
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DtoActivityJoinGroupDetail`
        """
        model = DtoActivityJoinGroupDetail()
        if include_optional:
            return DtoActivityJoinGroupDetail(
                create_at = '',
                detail = cnb_api.models.dto/organization_union.dto.OrganizationUnion(
                    all_member_count = 56, 
                    all_sub_group_count = 56, 
                    all_sub_mission_count = 56, 
                    all_sub_registry_count = 56, 
                    all_sub_repo_count = 56, 
                    created_at = '', 
                    description = '', 
                    domain = '', 
                    email = '', 
                    follow_count = 56, 
                    freeze = True, 
                    has_sub_group = True, 
                    id = 56, 
                    member_count = 56, 
                    name = '', 
                    path = '', 
                    remark = '', 
                    site = '', 
                    sub_group_count = 56, 
                    sub_mission_count = 56, 
                    sub_registry_count = 56, 
                    sub_repo_count = 56, 
                    updated_at = '', 
                    wechat_mp = '', ),
                remark = ''
            )
        else:
            return DtoActivityJoinGroupDetail(
        )
        """

    def testDtoActivityJoinGroupDetail(self):
        """Test DtoActivityJoinGroupDetail"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
