# coding: utf-8

"""
    CNB OPENAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Contact: cnb@tencent.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cnb_api.models.web_entry import WebEntry

class TestWebEntry(unittest.TestCase):
    """WebEntry unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WebEntry:
        """Test WebEntry
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WebEntry`
        """
        model = WebEntry()
        if include_optional:
            return WebEntry(
                entries = [
                    cnb_api.models.web/sub_entry.web.SubEntry(
                        name = '', 
                        path = '', 
                        sha = '', 
                        type = '', )
                    ],
                name = '',
                path = '',
                type = ''
            )
        else:
            return WebEntry(
        )
        """

    def testWebEntry(self):
        """Test WebEntry"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
