# coding: utf-8

"""
    CNB OPENAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Contact: cnb@tencent.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cnb_api.models.chart_metadata import ChartMetadata

class TestChartMetadata(unittest.TestCase):
    """ChartMetadata unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ChartMetadata:
        """Test ChartMetadata
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ChartMetadata`
        """
        model = ChartMetadata()
        if include_optional:
            return ChartMetadata(
                annotations = {
                    'key' : ''
                    },
                api_version = '',
                app_version = '',
                condition = '',
                dependencies = [
                    cnb_api.models.chart/dependency.chart.Dependency(
                        alias = '', 
                        condition = '', 
                        enabled = True, 
                        import_values = [
                            None
                            ], 
                        name = '', 
                        repository = '', 
                        tags = [
                            ''
                            ], 
                        version = '', )
                    ],
                deprecated = True,
                description = '',
                home = '',
                icon = '',
                keywords = [
                    ''
                    ],
                kube_version = '',
                maintainers = [
                    cnb_api.models.chart/maintainer.chart.Maintainer(
                        email = '', 
                        name = '', 
                        url = '', )
                    ],
                name = '',
                sources = [
                    ''
                    ],
                tags = '',
                type = '',
                version = ''
            )
        else:
            return ChartMetadata(
        )
        """

    def testChartMetadata(self):
        """Test ChartMetadata"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
