# coding: utf-8

"""
    CNB OPENAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Contact: cnb@tencent.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cnb_api.api.git_settings_api import GitSettingsApi


class TestGitSettingsApi(unittest.TestCase):
    """GitSettingsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = GitSettingsApi()

    def tearDown(self) -> None:
        pass

    def test_delete_branch_protection(self) -> None:
        """Test case for delete_branch_protection

        删除仓库保护分支规则。 Delete branch protection rule.
        """
        pass

    def test_get_branch_protection(self) -> None:
        """Test case for get_branch_protection

        查询仓库保护分支规则。Get branch protection rule.
        """
        pass

    def test_get_pipeline_settings(self) -> None:
        """Test case for get_pipeline_settings

        查询仓库云原生构建设置。List pipeline settings.
        """
        pass

    def test_get_pull_request_settings(self) -> None:
        """Test case for get_pull_request_settings

        查询仓库合并请求设置。List pull request settings.
        """
        pass

    def test_get_push_limit_settings(self) -> None:
        """Test case for get_push_limit_settings

        查询仓库推送设置。List push limit settings.
        """
        pass

    def test_list_branch_protections(self) -> None:
        """Test case for list_branch_protections

        查询仓库保护分支规则列表。List branch protection rules.
        """
        pass

    def test_patch_branch_protection(self) -> None:
        """Test case for patch_branch_protection

        更新仓库保护分支规则。Update branch protection rule.
        """
        pass

    def test_post_branch_protection(self) -> None:
        """Test case for post_branch_protection

        新增仓库保护分支规则。Create branch protection rule.
        """
        pass

    def test_put_pipeline_settings(self) -> None:
        """Test case for put_pipeline_settings

        更新仓库云原生构建设置。Update pipeline settings.
        """
        pass

    def test_put_pull_request_settings(self) -> None:
        """Test case for put_pull_request_settings

        设置仓库推送设置。Set pull request settings.
        """
        pass

    def test_put_push_limit_settings(self) -> None:
        """Test case for put_push_limit_settings

        设置仓库推送设置。Set push limit settings.
        """
        pass


if __name__ == '__main__':
    unittest.main()
