# coding: utf-8

"""
    CNB OPENAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Contact: cnb@tencent.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cnb_api.models.dto_outside_collaborator_in_repo import DtoOutsideCollaboratorInRepo

class TestDtoOutsideCollaboratorInRepo(unittest.TestCase):
    """DtoOutsideCollaboratorInRepo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DtoOutsideCollaboratorInRepo:
        """Test DtoOutsideCollaboratorInRepo
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DtoOutsideCollaboratorInRepo`
        """
        model = DtoOutsideCollaboratorInRepo()
        if include_optional:
            return DtoOutsideCollaboratorInRepo(
                access_level = 0,
                avatar = '',
                created_at = '',
                email = '',
                freeze = True,
                id = '',
                join_time = '',
                nickname = '',
                type = 0,
                username = '',
                verified = 56,
                verified_expire_in = ''
            )
        else:
            return DtoOutsideCollaboratorInRepo(
        )
        """

    def testDtoOutsideCollaboratorInRepo(self):
        """Test DtoOutsideCollaboratorInRepo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
