# coding: utf-8

"""
    CNB OPENAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Contact: cnb@tencent.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cnb_api.models.api_pull_request import ApiPullRequest

class TestApiPullRequest(unittest.TestCase):
    """ApiPullRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiPullRequest:
        """Test ApiPullRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiPullRequest`
        """
        model = ApiPullRequest()
        if include_optional:
            return ApiPullRequest(
                assignees = [
                    cnb_api.models.git_woa_com_cnb_monorepo_git_internal_app_git_service_bff_api/user_info.git_woa_com_cnb_monorepo_git_internal_app_git_service_bff_api.UserInfo(
                        freeze = True, 
                        nickname = '', 
                        username = '', )
                    ],
                author = cnb_api.models.git_woa_com_cnb_monorepo_git_internal_app_git_service_bff_api/user_info.git_woa_com_cnb_monorepo_git_internal_app_git_service_bff_api.UserInfo(
                    freeze = True, 
                    nickname = '', 
                    username = '', ),
                base = cnb_api.models.api/pull_ref.api.PullRef(
                    ref = '', 
                    repo = cnb_api.models.api/repo.api.Repo(
                        id = '', 
                        name = '', 
                        path = '', 
                        web_url = '', ), 
                    sha = '', ),
                blocked_on = '',
                comment_count = 56,
                created_at = '',
                head = cnb_api.models.api/pull_ref.api.PullRef(
                    ref = '', 
                    repo = cnb_api.models.api/repo.api.Repo(
                        id = '', 
                        name = '', 
                        path = '', 
                        web_url = '', ), 
                    sha = '', ),
                last_acted_at = '',
                mergeable_state = '',
                merged_by = cnb_api.models.git_woa_com_cnb_monorepo_git_internal_app_git_service_bff_api/user_info.git_woa_com_cnb_monorepo_git_internal_app_git_service_bff_api.UserInfo(
                    freeze = True, 
                    nickname = '', 
                    username = '', ),
                number = '',
                repo = cnb_api.models.api/repo.api.Repo(
                    id = '', 
                    name = '', 
                    path = '', 
                    web_url = '', ),
                review_count = 56,
                state = '',
                title = '',
                updated_at = ''
            )
        else:
            return ApiPullRequest(
        )
        """

    def testApiPullRequest(self):
        """Test ApiPullRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
