# coding: utf-8

"""
    CNB OPENAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Contact: cnb@tencent.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cnb_api.models.web_overview_branches import WebOverviewBranches

class TestWebOverviewBranches(unittest.TestCase):
    """WebOverviewBranches unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WebOverviewBranches:
        """Test WebOverviewBranches
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WebOverviewBranches`
        """
        model = WebOverviewBranches()
        if include_optional:
            return WebOverviewBranches(
                active_branches = [
                    cnb_api.models.web/branch_list_item.web.BranchListItem(
                        ahead = 56, 
                        associated_pull_request = cnb_api.models.web/branch_pull_request.web.BranchPullRequest(
                            is_merged = True, 
                            mergeable_state = '', 
                            number = '', 
                            state = '', ), 
                        behind = 56, 
                        commit = cnb_api.models.web/commit.web.Commit(
                            author = cnb_api.models.git_woa_com_cnb_monorepo_git_internal_app_git_service_bff_web/user_info.git_woa_com_cnb_monorepo_git_internal_app_git_service_bff_web.UserInfo(
                                freeze = True, 
                                nickname = '', 
                                username = '', ), 
                            commit_statuses = cnb_api.models.web/commit_statuses.web.CommitStatuses(
                                sha = '', 
                                state = '', 
                                statuses = [
                                    cnb_api.models.web/commit_status.web.CommitStatus(
                                        context = '', 
                                        created_at = '', 
                                        description = '', 
                                        state = '', 
                                        target_url = '', 
                                        updated_at = '', )
                                    ], ), 
                            committer = cnb_api.models.git_woa_com_cnb_monorepo_git_internal_app_git_service_bff_web/user_info.git_woa_com_cnb_monorepo_git_internal_app_git_service_bff_web.UserInfo(
                                freeze = True, 
                                nickname = '', 
                                username = '', ), 
                            files = cnb_api.models.web/commit_files.web.CommitFiles(
                                base_commit = '', 
                                diff = cnb_api.models.web/diff.web.Diff(
                                    base_commit = '', 
                                    file_exceeded = True, 
                                    file_limit = 56, 
                                    head_commit = '', 
                                    stat = cnb_api.models.web/diff_stat.web.DiffStat(
                                        deletions = 56, 
                                        entry_exceeded = True, 
                                        entry_limit = 56, 
                                        insertions = 56, 
                                        paths = [
                                            cnb_api.models.web/diff_entry.web.DiffEntry(
                                                change_type = '', 
                                                deletions = 56, 
                                                file_index = 56, 
                                                insertions = 56, 
                                                is_bin = True, 
                                                old_path = '', 
                                                path = '', )
                                            ], ), ), 
                                head_commit = '', 
                                straight = True, ), 
                            parents = [
                                cnb_api.models.web/commit_parent.web.CommitParent(
                                    sha = '', )
                                ], 
                            sha = '', ), 
                        dev_meta = [
                            56
                            ], 
                        is_head = True, 
                        is_protected = True, 
                        name = '', )
                    ],
                default_branch = cnb_api.models.web/branch_list_item.web.BranchListItem(
                    ahead = 56, 
                    associated_pull_request = cnb_api.models.web/branch_pull_request.web.BranchPullRequest(
                        is_merged = True, 
                        mergeable_state = '', 
                        number = '', 
                        state = '', ), 
                    behind = 56, 
                    commit = cnb_api.models.web/commit.web.Commit(
                        author = cnb_api.models.git_woa_com_cnb_monorepo_git_internal_app_git_service_bff_web/user_info.git_woa_com_cnb_monorepo_git_internal_app_git_service_bff_web.UserInfo(
                            freeze = True, 
                            nickname = '', 
                            username = '', ), 
                        commit_statuses = cnb_api.models.web/commit_statuses.web.CommitStatuses(
                            sha = '', 
                            state = '', 
                            statuses = [
                                cnb_api.models.web/commit_status.web.CommitStatus(
                                    context = '', 
                                    created_at = '', 
                                    description = '', 
                                    state = '', 
                                    target_url = '', 
                                    updated_at = '', )
                                ], ), 
                        committer = cnb_api.models.git_woa_com_cnb_monorepo_git_internal_app_git_service_bff_web/user_info.git_woa_com_cnb_monorepo_git_internal_app_git_service_bff_web.UserInfo(
                            freeze = True, 
                            nickname = '', 
                            username = '', ), 
                        files = cnb_api.models.web/commit_files.web.CommitFiles(
                            base_commit = '', 
                            diff = cnb_api.models.web/diff.web.Diff(
                                base_commit = '', 
                                file_exceeded = True, 
                                file_limit = 56, 
                                head_commit = '', 
                                stat = cnb_api.models.web/diff_stat.web.DiffStat(
                                    deletions = 56, 
                                    entry_exceeded = True, 
                                    entry_limit = 56, 
                                    insertions = 56, 
                                    paths = [
                                        cnb_api.models.web/diff_entry.web.DiffEntry(
                                            change_type = '', 
                                            deletions = 56, 
                                            file_index = 56, 
                                            insertions = 56, 
                                            is_bin = True, 
                                            old_path = '', 
                                            path = '', )
                                        ], ), ), 
                            head_commit = '', 
                            straight = True, ), 
                        parents = [
                            cnb_api.models.web/commit_parent.web.CommitParent(
                                sha = '', )
                            ], 
                        sha = '', ), 
                    dev_meta = [
                        56
                        ], 
                    is_head = True, 
                    is_protected = True, 
                    name = '', ),
                has_more_active_branch = True,
                has_more_stale_branch = True,
                has_more_yours_branch = True,
                initialized = True,
                stale_branches = [
                    cnb_api.models.web/branch_list_item.web.BranchListItem(
                        ahead = 56, 
                        associated_pull_request = cnb_api.models.web/branch_pull_request.web.BranchPullRequest(
                            is_merged = True, 
                            mergeable_state = '', 
                            number = '', 
                            state = '', ), 
                        behind = 56, 
                        commit = cnb_api.models.web/commit.web.Commit(
                            author = cnb_api.models.git_woa_com_cnb_monorepo_git_internal_app_git_service_bff_web/user_info.git_woa_com_cnb_monorepo_git_internal_app_git_service_bff_web.UserInfo(
                                freeze = True, 
                                nickname = '', 
                                username = '', ), 
                            commit_statuses = cnb_api.models.web/commit_statuses.web.CommitStatuses(
                                sha = '', 
                                state = '', 
                                statuses = [
                                    cnb_api.models.web/commit_status.web.CommitStatus(
                                        context = '', 
                                        created_at = '', 
                                        description = '', 
                                        state = '', 
                                        target_url = '', 
                                        updated_at = '', )
                                    ], ), 
                            committer = cnb_api.models.git_woa_com_cnb_monorepo_git_internal_app_git_service_bff_web/user_info.git_woa_com_cnb_monorepo_git_internal_app_git_service_bff_web.UserInfo(
                                freeze = True, 
                                nickname = '', 
                                username = '', ), 
                            files = cnb_api.models.web/commit_files.web.CommitFiles(
                                base_commit = '', 
                                diff = cnb_api.models.web/diff.web.Diff(
                                    base_commit = '', 
                                    file_exceeded = True, 
                                    file_limit = 56, 
                                    head_commit = '', 
                                    stat = cnb_api.models.web/diff_stat.web.DiffStat(
                                        deletions = 56, 
                                        entry_exceeded = True, 
                                        entry_limit = 56, 
                                        insertions = 56, 
                                        paths = [
                                            cnb_api.models.web/diff_entry.web.DiffEntry(
                                                change_type = '', 
                                                deletions = 56, 
                                                file_index = 56, 
                                                insertions = 56, 
                                                is_bin = True, 
                                                old_path = '', 
                                                path = '', )
                                            ], ), ), 
                                head_commit = '', 
                                straight = True, ), 
                            parents = [
                                cnb_api.models.web/commit_parent.web.CommitParent(
                                    sha = '', )
                                ], 
                            sha = '', ), 
                        dev_meta = [
                            56
                            ], 
                        is_head = True, 
                        is_protected = True, 
                        name = '', )
                    ],
                yours_branches = [
                    cnb_api.models.web/branch_list_item.web.BranchListItem(
                        ahead = 56, 
                        associated_pull_request = cnb_api.models.web/branch_pull_request.web.BranchPullRequest(
                            is_merged = True, 
                            mergeable_state = '', 
                            number = '', 
                            state = '', ), 
                        behind = 56, 
                        commit = cnb_api.models.web/commit.web.Commit(
                            author = cnb_api.models.git_woa_com_cnb_monorepo_git_internal_app_git_service_bff_web/user_info.git_woa_com_cnb_monorepo_git_internal_app_git_service_bff_web.UserInfo(
                                freeze = True, 
                                nickname = '', 
                                username = '', ), 
                            commit_statuses = cnb_api.models.web/commit_statuses.web.CommitStatuses(
                                sha = '', 
                                state = '', 
                                statuses = [
                                    cnb_api.models.web/commit_status.web.CommitStatus(
                                        context = '', 
                                        created_at = '', 
                                        description = '', 
                                        state = '', 
                                        target_url = '', 
                                        updated_at = '', )
                                    ], ), 
                            committer = cnb_api.models.git_woa_com_cnb_monorepo_git_internal_app_git_service_bff_web/user_info.git_woa_com_cnb_monorepo_git_internal_app_git_service_bff_web.UserInfo(
                                freeze = True, 
                                nickname = '', 
                                username = '', ), 
                            files = cnb_api.models.web/commit_files.web.CommitFiles(
                                base_commit = '', 
                                diff = cnb_api.models.web/diff.web.Diff(
                                    base_commit = '', 
                                    file_exceeded = True, 
                                    file_limit = 56, 
                                    head_commit = '', 
                                    stat = cnb_api.models.web/diff_stat.web.DiffStat(
                                        deletions = 56, 
                                        entry_exceeded = True, 
                                        entry_limit = 56, 
                                        insertions = 56, 
                                        paths = [
                                            cnb_api.models.web/diff_entry.web.DiffEntry(
                                                change_type = '', 
                                                deletions = 56, 
                                                file_index = 56, 
                                                insertions = 56, 
                                                is_bin = True, 
                                                old_path = '', 
                                                path = '', )
                                            ], ), ), 
                                head_commit = '', 
                                straight = True, ), 
                            parents = [
                                cnb_api.models.web/commit_parent.web.CommitParent(
                                    sha = '', )
                                ], 
                            sha = '', ), 
                        dev_meta = [
                            56
                            ], 
                        is_head = True, 
                        is_protected = True, 
                        name = '', )
                    ]
            )
        else:
            return WebOverviewBranches(
        )
        """

    def testWebOverviewBranches(self):
        """Test WebOverviewBranches"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
