# coding: utf-8

"""
    CNB OPENAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Contact: cnb@tencent.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cnb_api.models.constant_repo_display_module import ConstantRepoDisplayModule

class TestConstantRepoDisplayModule(unittest.TestCase):
    """ConstantRepoDisplayModule unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testConstantRepoDisplayModule(self):
        """Test ConstantRepoDisplayModule"""
        # inst = ConstantRepoDisplayModule()

if __name__ == '__main__':
    unittest.main()
