# coding: utf-8

"""
    CNB OPENAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Contact: cnb@tencent.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cnb_api.models.webapi_update_pull_request_form import WebapiUpdatePullRequestForm

class TestWebapiUpdatePullRequestForm(unittest.TestCase):
    """WebapiUpdatePullRequestForm unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WebapiUpdatePullRequestForm:
        """Test WebapiUpdatePullRequestForm
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WebapiUpdatePullRequestForm`
        """
        model = WebapiUpdatePullRequestForm()
        if include_optional:
            return WebapiUpdatePullRequestForm(
                body = '',
                state = '',
                title = ''
            )
        else:
            return WebapiUpdatePullRequestForm(
        )
        """

    def testWebapiUpdatePullRequestForm(self):
        """Test WebapiUpdatePullRequestForm"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
