# coding: utf-8

"""
    CNB OPENAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Contact: cnb@tencent.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cnb_api.models.web_pull_request_repository import WebPullRequestRepository

class TestWebPullRequestRepository(unittest.TestCase):
    """WebPullRequestRepository unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WebPullRequestRepository:
        """Test WebPullRequestRepository
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WebPullRequestRepository`
        """
        model = WebPullRequestRepository()
        if include_optional:
            return WebPullRequestRepository(
                access_role = 56,
                deleted = True,
                ref = '',
                slug = '',
                usage = cnb_api.models.web/repository_usage.web.RepositoryUsage(
                    git_size_in_kib = '', 
                    lfs_size_in_kib = '', )
            )
        else:
            return WebPullRequestRepository(
        )
        """

    def testWebPullRequestRepository(self):
        """Test WebPullRequestRepository"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
