# coding: utf-8

"""
    CNB OPENAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Contact: cnb@tencent.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cnb_api.models.dto_container_tag import DtoContainerTag

class TestDtoContainerTag(unittest.TestCase):
    """DtoContainerTag unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DtoContainerTag:
        """Test DtoContainerTag
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DtoContainerTag`
        """
        model = DtoContainerTag()
        if include_optional:
            return DtoContainerTag(
                address = '',
                annotations = cnb_api.models.dto/container_annotation.dto.ContainerAnnotation(
                    revision = '', 
                    version = '', ),
                images = [
                    cnb_api.models.dto/container_image.dto.ContainerImage(
                        arch = '', 
                        digest = '', 
                        layers = [
                            cnb_api.models.dto/container_image_layer.dto.ContainerImageLayer(
                                instruction = '', 
                                size = 56, )
                            ], 
                        os = '', 
                        size = 56, )
                    ],
                last_pusher = cnb_api.models.dto/last_pusher.dto.LastPusher(
                    is_frozen = True, 
                    name = '', 
                    nickname = '', 
                    push_at = '', ),
                name = '',
                pull_count = 56,
                recent_pull_count = 56
            )
        else:
            return DtoContainerTag(
        )
        """

    def testDtoContainerTag(self):
        """Test DtoContainerTag"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
