# coding: utf-8

"""
    CNB OPENAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Contact: cnb@tencent.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cnb_api.models.web_branch_pull_request import WebBranchPullRequest

class TestWebBranchPullRequest(unittest.TestCase):
    """WebBranchPullRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WebBranchPullRequest:
        """Test WebBranchPullRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WebBranchPullRequest`
        """
        model = WebBranchPullRequest()
        if include_optional:
            return WebBranchPullRequest(
                is_merged = True,
                mergeable_state = '',
                number = '',
                state = ''
            )
        else:
            return WebBranchPullRequest(
        )
        """

    def testWebBranchPullRequest(self):
        """Test WebBranchPullRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
