# coding: utf-8

"""
    CNB OPENAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Contact: cnb@tencent.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cnb_api.models.dto_special_amount import DtoSpecialAmount

class TestDtoSpecialAmount(unittest.TestCase):
    """DtoSpecialAmount unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DtoSpecialAmount:
        """Test DtoSpecialAmount
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DtoSpecialAmount`
        """
        model = DtoSpecialAmount()
        if include_optional:
            return DtoSpecialAmount(
                compute_build_corehour = 56,
                compute_build_desc = '',
                compute_build_expire = '',
                compute_develop_corehour = 56,
                compute_develop_desc = '',
                compute_develop_expire = '',
                storage_git_desc = '',
                storage_git_expire = '',
                storage_git_gib = 56,
                storage_object_desc = '',
                storage_object_expire = '',
                storage_object_gib = 56
            )
        else:
            return DtoSpecialAmount(
        )
        """

    def testDtoSpecialAmount(self):
        """Test DtoSpecialAmount"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
