# Generated by Django 4.2.20 on 2025-04-19 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0003_alter_referralreward_tier_basis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referralreward',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('WIRE', 'Wire Transfer'), ('CRYPTO', 'Cryptocurrency'), ('CARD', 'Credit/Debit Card'), ('MANUAL', 'Manual'), ('SYSTEM', 'System Generated'), ('UPI', 'UPI Payment')], help_text='Specific payment method to simulate for deposit rewards (optional).', max_length=50, null=True),
        ),
    ]
