// This file is autogenerated. DO NOT EDIT

#pragma once
#include <robotpy_build.h>

#include <rpy/Notifier.h>

namespace frc {

template <typename CfgBase = rpygen::EmptyTrampolineCfg>
struct PyTrampolineCfg_PyNotifier : CfgBase
{
  using Base = frc::PyNotifier;
};

template <typename PyTrampolineBase, typename PyTrampolineCfg>
struct PyTrampoline_PyNotifier : PyTrampolineBase {
  using PyTrampolineBase::PyTrampolineBase;
};

}; // namespace frc
