from typing import List

class PyBytePairTokenizer:
    def __init__(self): ...
    @property
    def size(self) -> int: ...
    def fit(self, corpus: List[int], max_vocab_size: int, n_iter: int) -> None: ...
    def encode(self, text: bytes) -> list[int]: ...
    def encode_corpus(self, corpus: List[int]) -> List[int]: ...
    def decode(self, tokens: List[int]) -> bytes: ...

def data_loader(filepath: str) -> List[int]: ...
def data_saver(corpus: List[int], filepath: str) -> None: ...
