'            '|   0|'(x*y)       ' Σ(Θ('pos') Λ(<function <lambda> at 0x00000197996a1ec0>) POS(0) Π(*3) Θ('pos') Λ(<function <lambda> at 0x00000197996a1f60>) RPOS(0)) trying(0)...
'            '|   0|'(x*y)       ' Θ(pos) SUCCESS
'            '|   0|'(x*y)       ' Λ(function) evaluating...
'            '|   0|'(x*y)       ' Λ(function) SUCCESS
'            '|   0|'(x*y)       ' POS(0) SUCCESS(0,0)=
'            '|   0|'(x*y)       ' Π(Σ(*3) Σ(*2) Π(*3)) trying(0)...
'            '|   0|'(x*y)       ' Σ(Π(*3) ANY('+-*/') ζ('X')) trying(0)...
'            '|   0|'(x*y)       ' Π(ANY('abcdefghijklmnopqrstuvwxyz') SPAN('0123456789') Σ(*3)) trying(0)...
'            '|   0|'(x*y)       ' ANY('abcdefghijklmnopqrstuvwxyz') trying(0)
'            '|   0|'(x*y)       ' SPAN('0123456789') trying(0)
'            '|   0|'(x*y)       ' Σ(σ('(') ζ('X') σ(')')) trying(0)...
'            '|   0|'(x*y)       ' σ('(') trying(0)
'            '|   0|'(x*y)       ' σ('(') SUCCESS(0,1)=
'           ('|   1|'x*y)        ' Π(Σ(*3) Σ(*2) Π(*3)) trying(1)...
'           ('|   1|'x*y)        ' Σ(Π(*3) ANY('+-*/') ζ('X')) trying(1)...
'           ('|   1|'x*y)        ' Π(ANY('abcdefghijklmnopqrstuvwxyz') SPAN('0123456789') Σ(*3)) trying(1)...
'           ('|   1|'x*y)        ' ANY('abcdefghijklmnopqrstuvwxyz') trying(1)
'           ('|   1|'x*y)        ' ANY('abcdefghijklmnopqrstuvwxyz') SUCCESS(1,1)=x
'          (x'|   2|'*y)         ' ANY('+-*/') trying(2)
'          (x'|   2|'*y)         ' ANY('+-*/') SUCCESS(2,1)=*
'         (x*'|   3|'y)          ' Π(Σ(*3) Σ(*2) Π(*3)) trying(3)...
'         (x*'|   3|'y)          ' Σ(Π(*3) ANY('+-*/') ζ('X')) trying(3)...
'         (x*'|   3|'y)          ' Π(ANY('abcdefghijklmnopqrstuvwxyz') SPAN('0123456789') Σ(*3)) trying(3)...
'         (x*'|   3|'y)          ' ANY('abcdefghijklmnopqrstuvwxyz') trying(3)
'         (x*'|   3|'y)          ' ANY('abcdefghijklmnopqrstuvwxyz') SUCCESS(3,1)=y
'        (x*y'|   4|')           ' ANY('+-*/') trying(4)
'        (x*y'|   4|')           ' ANY('abcdefghijklmnopqrstuvwxyz') backtracking(3,4)...
'         (x*'|   3|'y)          ' SPAN('0123456789') trying(3)
'         (x*'|   3|'y)          ' Σ(σ('(') ζ('X') σ(')')) trying(3)...
'         (x*'|   3|'y)          ' σ('(') trying(3)
'         (x*'|   3|'y)          ' Σ(ANY('+-') ζ('X')) trying(3)...
'         (x*'|   3|'y)          ' ANY('+-') trying(3)
'         (x*'|   3|'y)          ' Π(ANY('abcdefghijklmnopqrstuvwxyz') SPAN('0123456789') Σ(*3)) trying(3)...
'         (x*'|   3|'y)          ' ANY('abcdefghijklmnopqrstuvwxyz') trying(3)
'         (x*'|   3|'y)          ' ANY('abcdefghijklmnopqrstuvwxyz') SUCCESS(3,1)=y
'        (x*y'|   4|')           ' Σ(*) SUCCESS(1,3)=x*y
'        (x*y'|   4|')           ' σ(')') trying(4)
'        (x*y'|   4|')           ' σ(')') SUCCESS(4,1)=
'       (x*y)'|   5|'            ' Σ(*) SUCCESS(0,5)=(x*y)
'       (x*y)'|   5|'            ' ANY('+-*/') trying(5)
'       (x*y)'|   5|'            ' Σ(*) backtracking(0, 5)...
'        (x*y'|   4|')           ' σ(')') backtracking(4)...
'        (x*y'|   4|')           ' Σ(*) backtracking(1, 4)...
'        (x*y'|   4|')           ' ANY('abcdefghijklmnopqrstuvwxyz') backtracking(3,4)...
'         (x*'|   3|'y)          ' SPAN('0123456789') trying(3)
'         (x*'|   3|'y)          ' Σ(σ('(') ζ('X') σ(')')) trying(3)...
'         (x*'|   3|'y)          ' σ('(') trying(3)
'         (x*'|   3|'y)          ' ANY('+-*/') backtracking(2,3)...
'          (x'|   2|'*y)         ' ANY('abcdefghijklmnopqrstuvwxyz') backtracking(1,2)...
'           ('|   1|'x*y)        ' SPAN('0123456789') trying(1)
'           ('|   1|'x*y)        ' Σ(σ('(') ζ('X') σ(')')) trying(1)...
'           ('|   1|'x*y)        ' σ('(') trying(1)
'           ('|   1|'x*y)        ' Σ(ANY('+-') ζ('X')) trying(1)...
'           ('|   1|'x*y)        ' ANY('+-') trying(1)
'           ('|   1|'x*y)        ' Π(ANY('abcdefghijklmnopqrstuvwxyz') SPAN('0123456789') Σ(*3)) trying(1)...
'           ('|   1|'x*y)        ' ANY('abcdefghijklmnopqrstuvwxyz') trying(1)
'           ('|   1|'x*y)        ' ANY('abcdefghijklmnopqrstuvwxyz') SUCCESS(1,1)=x
'          (x'|   2|'*y)         ' σ(')') trying(2)
'          (x'|   2|'*y)         ' ANY('abcdefghijklmnopqrstuvwxyz') backtracking(1,2)...
'           ('|   1|'x*y)        ' SPAN('0123456789') trying(1)
'           ('|   1|'x*y)        ' Σ(σ('(') ζ('X') σ(')')) trying(1)...
'           ('|   1|'x*y)        ' σ('(') trying(1)
'            '|   0|'(x*y)       ' σ('(') backtracking(0)...
'            '|   0|'(x*y)       ' Σ(ANY('+-') ζ('X')) trying(0)...
'            '|   0|'(x*y)       ' ANY('+-') trying(0)
'            '|   0|'(x*y)       ' Π(ANY('abcdefghijklmnopqrstuvwxyz') SPAN('0123456789') Σ(*3)) trying(0)...
'            '|   0|'(x*y)       ' ANY('abcdefghijklmnopqrstuvwxyz') trying(0)
'            '|   0|'(x*y)       ' SPAN('0123456789') trying(0)
'            '|   0|'(x*y)       ' Σ(σ('(') ζ('X') σ(')')) trying(0)...
'            '|   0|'(x*y)       ' σ('(') trying(0)
'            '|   0|'(x*y)       ' σ('(') SUCCESS(0,1)=
'           ('|   1|'x*y)        ' Π(Σ(*3) Σ(*2) Π(*3)) trying(1)...
'           ('|   1|'x*y)        ' Σ(Π(*3) ANY('+-*/') ζ('X')) trying(1)...
'           ('|   1|'x*y)        ' Π(ANY('abcdefghijklmnopqrstuvwxyz') SPAN('0123456789') Σ(*3)) trying(1)...
'           ('|   1|'x*y)        ' ANY('abcdefghijklmnopqrstuvwxyz') trying(1)
'           ('|   1|'x*y)        ' ANY('abcdefghijklmnopqrstuvwxyz') SUCCESS(1,1)=x
'          (x'|   2|'*y)         ' ANY('+-*/') trying(2)
'          (x'|   2|'*y)         ' ANY('+-*/') SUCCESS(2,1)=*
'         (x*'|   3|'y)          ' Π(Σ(*3) Σ(*2) Π(*3)) trying(3)...
'         (x*'|   3|'y)          ' Σ(Π(*3) ANY('+-*/') ζ('X')) trying(3)...
'         (x*'|   3|'y)          ' Π(ANY('abcdefghijklmnopqrstuvwxyz') SPAN('0123456789') Σ(*3)) trying(3)...
'         (x*'|   3|'y)          ' ANY('abcdefghijklmnopqrstuvwxyz') trying(3)
'         (x*'|   3|'y)          ' ANY('abcdefghijklmnopqrstuvwxyz') SUCCESS(3,1)=y
'        (x*y'|   4|')           ' ANY('+-*/') trying(4)
'        (x*y'|   4|')           ' ANY('abcdefghijklmnopqrstuvwxyz') backtracking(3,4)...
'         (x*'|   3|'y)          ' SPAN('0123456789') trying(3)
'         (x*'|   3|'y)          ' Σ(σ('(') ζ('X') σ(')')) trying(3)...
'         (x*'|   3|'y)          ' σ('(') trying(3)
'         (x*'|   3|'y)          ' Σ(ANY('+-') ζ('X')) trying(3)...
'         (x*'|   3|'y)          ' ANY('+-') trying(3)
'         (x*'|   3|'y)          ' Π(ANY('abcdefghijklmnopqrstuvwxyz') SPAN('0123456789') Σ(*3)) trying(3)...
'         (x*'|   3|'y)          ' ANY('abcdefghijklmnopqrstuvwxyz') trying(3)
'         (x*'|   3|'y)          ' ANY('abcdefghijklmnopqrstuvwxyz') SUCCESS(3,1)=y
'        (x*y'|   4|')           ' Σ(*) SUCCESS(1,3)=x*y
'        (x*y'|   4|')           ' σ(')') trying(4)
'        (x*y'|   4|')           ' σ(')') SUCCESS(4,1)=
'       (x*y)'|   5|'            ' Σ(*) SUCCESS(0,5)=(x*y)
'       (x*y)'|   5|'            ' Θ(pos) SUCCESS
'       (x*y)'|   5|'            ' Λ(function) evaluating...
'       (x*y)'|   5|'            ' Λ(function) SUCCESS
'       (x*y)'|   5|'            ' RPOS(0) SUCCESS(5,0)=
'       (x*y)'|   5|'            ' Σ(*) SUCCESS(0,5)=(x*y)
'       (x*y)'|   5|'            ' SEARCH(): "(x*y)" ? "slice(0, 5, None)"
P0·R5·