from pandapipes.constants import *

CELSIUS_TO_K = NORMAL_TEMPERATURE
TEMPERATURE_CONVERGENCE_THRESHOLD_C = 1


class HeatExchangerControl:
    OUT_OF_RANGE_THRESHOLD = 36.5
    MIN_PRIMARY_MASS_FLOW_KG_PER_S = 0.05555556
    DICHOTOMY_CONVERGENCE_THRESHOLD = 1e-12
