// This file is autogenerated. DO NOT EDIT

#pragma once
#include <robotpy_build.h>

#include <frc/smartdashboard/MechanismObject2d.h>

#include <frc/smartdashboard/MechanismLigament2d.h>

namespace frc {

template <typename CfgBase = rpygen::EmptyTrampolineCfg>
struct PyTrampolineCfg_MechanismObject2d : CfgBase
{
  using Base = frc::MechanismObject2d;
  using override_base_UpdateEntries_Tshared_ptr = frc::MechanismObject2d;
};

template <typename PyTrampolineBase, typename PyTrampolineCfg>
struct PyTrampoline_MechanismObject2d : PyTrampolineBase {
  using PyTrampolineBase::PyTrampolineBase;

  #ifndef RPYGEN_DISABLE_UpdateEntries_Tshared_ptr
    void UpdateEntries(std::shared_ptr<nt::NetworkTable> table) override {
      using LookupBase = typename PyTrampolineCfg::Base;
      RPYBUILD_OVERRIDE_PURE_NAME(MechanismObject2d, PYBIND11_TYPE(void), LookupBase,
        "_updateEntries", UpdateEntries, table);
    }
  #endif
};

}; // namespace frc
