from os.path import abspath, dirname, join

LOG_PREFIX: str = "[TTSVowelViz] ➺"
FILE_NAME_PREFIX: str = "utterance_"

_TTSVOWELVIZ_PATH: str = dirname(p=dirname(p=abspath(path=__file__)))

_DATA_DIRECTORY_NAME: str = "data"
DATA_DIRECTORY_PATH: str = join(_TTSVOWELVIZ_PATH, _DATA_DIRECTORY_NAME)

_TEXT_DIRECTORY_NAME: str = "text"
TEXT_DIRECTORY_PATH: str = join(DATA_DIRECTORY_PATH, _TEXT_DIRECTORY_NAME)

_SPEECH_DIRECTORY_NAME: str = "speech"
SPEECH_DIRECTORY_PATH: str = join(DATA_DIRECTORY_PATH, _SPEECH_DIRECTORY_NAME)
GROUND_TRUTH_DIRECTORY_NAME: str = "truth"
GROUND_TRUTH_DIRECTORY_PATH: str = join(SPEECH_DIRECTORY_PATH, GROUND_TRUTH_DIRECTORY_NAME)

_FORMANTS_DIRECTORY_NAME: str = "formants"
FORMANTS_DIRECTORY_PATH: str = join(DATA_DIRECTORY_PATH, _FORMANTS_DIRECTORY_NAME)
_STATIC_FORMANTS_FILE_NAME: str = "static_formants.csv"
STATIC_FORMANTS_FILE_PATH: str = join(FORMANTS_DIRECTORY_PATH, _STATIC_FORMANTS_FILE_NAME)
_DYNAMIC_FORMANTS_FILE_NAME: str = "dynamic_formants.csv"
DYNAMIC_FORMANTS_FILE_PATH: str = join(FORMANTS_DIRECTORY_PATH, _DYNAMIC_FORMANTS_FILE_NAME)

_VOWEL_SPACE_DIRECTORY_NAME: str = "vowel_spaces"
VOWEL_SPACE_DIRECTORY_PATH: str = join(DATA_DIRECTORY_PATH, _VOWEL_SPACE_DIRECTORY_NAME)
_STATIC_VOWEL_SPACE_FILE_NAME: str = "static_vowel_space.html"
STATIC_VOWEL_SPACE_FILE_PATH: str = join(VOWEL_SPACE_DIRECTORY_PATH, _STATIC_VOWEL_SPACE_FILE_NAME)
_DYNAMIC_VOWEL_SPACE_FILE_NAME: str = "dynamic_vowel_space.html"
DYNAMIC_VOWEL_SPACE_FILE_PATH: str = join(VOWEL_SPACE_DIRECTORY_PATH, _DYNAMIC_VOWEL_SPACE_FILE_NAME)
