__all__ = ['external_libs']

class external_libs:
    class test_lib:
        def __init__(self) -> None: ...
        def func1(self, string: str): ...
        def func2(self, a: int, b: int) -> int: ...
        def func3(self) -> float: ...
