from PyQt5.QtCore import QRect
from PyQt5.QtWidgets import QMainWindow, QWidget

def get_center_screenGeometry(window: QWidget | QMainWindow, width: int = None, height: int = None) -> QRect | None: ...
def setAntiScreenShot(window: int | QWidget): ...

class n_qthread: ...
