def decode_prediction_8bit(data: bytearray) -> None: ...
def decode_prediction_16bit(data: bytearray) -> None: ...
def encode_prediction_8bit(data: bytearray) -> None: ...
def encode_prediction_16bit(data: bytearray) -> None: ...

def decode(data: bytes, height: int, width: int, depth: int, version: int) -> bytes: ...
def encode(data: bytes) -> bytes: ...
