import enum
from _typeshed import Incomplete

__all__ = ['AsyncThreadPool_Status', 'n_AsyncThreadPool']

class AsyncThreadPool_Status(enum.Enum):
    unstart: int
    running: int
    finish: int

class n_asyncerror(Exception): ...

class n_AsyncThreadPool:
    max_workers: Incomplete
    def __init__(self, max_workers: int = 5, group: int = 0, time_interval: float = 0.0) -> None: ...
    def setGroupExecInterval(self, group: int, time_interval: float): ...
    @property
    def getStatus(self) -> AsyncThreadPool_Status: ...
    def put(self, func, *args, **kwargs) -> None: ...
    def start(self) -> list: ...
    def get_results(self): ...
    @staticmethod
    def single_submit(func, *args, **kwargs) -> any: ...
    def clear(self) -> None: ...
    def map(self, func, *args) -> list: ...
    def __enter__(self): ...
    def __exit__(self, exc_type: type[BaseException] | None, exc_val: BaseException | None, exc_tb: types.TracebackType | None): ...
