# coding: utf-8

"""
    CNB OPENAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Contact: cnb@tencent.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from cnb_api.models.dto_container_annotation import DtoContainerAnnotation
from cnb_api.models.dto_container_image import DtoContainerImage
from cnb_api.models.dto_last_pusher import DtoLastPusher
from typing import Optional, Set
from typing_extensions import Self

class DtoContainerTag(BaseModel):
    """
    DtoContainerTag
    """ # noqa: E501
    address: Optional[StrictStr] = None
    annotations: Optional[DtoContainerAnnotation] = None
    images: Optional[List[DtoContainerImage]] = None
    last_pusher: Optional[DtoLastPusher] = None
    name: Optional[StrictStr] = None
    pull_count: Optional[StrictInt] = None
    recent_pull_count: Optional[StrictInt] = None
    __properties: ClassVar[List[str]] = ["address", "annotations", "images", "last_pusher", "name", "pull_count", "recent_pull_count"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DtoContainerTag from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of annotations
        if self.annotations:
            _dict['annotations'] = self.annotations.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in images (list)
        _items = []
        if self.images:
            for _item_images in self.images:
                if _item_images:
                    _items.append(_item_images.to_dict())
            _dict['images'] = _items
        # override the default output from pydantic by calling `to_dict()` of last_pusher
        if self.last_pusher:
            _dict['last_pusher'] = self.last_pusher.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DtoContainerTag from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "address": obj.get("address"),
            "annotations": DtoContainerAnnotation.from_dict(obj["annotations"]) if obj.get("annotations") is not None else None,
            "images": [DtoContainerImage.from_dict(_item) for _item in obj["images"]] if obj.get("images") is not None else None,
            "last_pusher": DtoLastPusher.from_dict(obj["last_pusher"]) if obj.get("last_pusher") is not None else None,
            "name": obj.get("name"),
            "pull_count": obj.get("pull_count"),
            "recent_pull_count": obj.get("recent_pull_count")
        })
        return _obj


