# coding: utf-8

"""
    CNB OPENAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Contact: cnb@tencent.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from cnb_api.models.organization_setting_value import OrganizationSettingValue
from typing import Optional, Set
from typing_extensions import Self

class DtoOrganizationSettingWithParent(BaseModel):
    """
    DtoOrganizationSettingWithParent
    """ # noqa: E501
    can_show_members: Optional[StrictBool] = Field(default=None, description="上级group设置了hide_members为1，则下级都不能显示")
    can_show_sub_groups: Optional[StrictBool] = Field(default=None, description="上级group设置了hide_sub_groups为1，则下级都不能显示")
    can_show_watermark: Optional[StrictBool] = None
    email_verification: Optional[StrictStr] = None
    group_protection: Optional[StrictInt] = None
    hide_members: Optional[StrictInt] = Field(default=None, description="是否对外隐藏组织成员，0 - 否, 1 - 是")
    hide_sub_groups: Optional[StrictInt] = Field(default=None, description="是否对外隐藏子组织，0 - 否, 1 - 是")
    root_email_verification: Optional[StrictStr] = None
    root_group_protection: Optional[StrictBool] = None
    root_values: Optional[OrganizationSettingValue] = None
    show_private_repo_watermark: Optional[StrictInt] = None
    values: Optional[OrganizationSettingValue] = None
    __properties: ClassVar[List[str]] = ["can_show_members", "can_show_sub_groups", "can_show_watermark", "email_verification", "group_protection", "hide_members", "hide_sub_groups", "root_email_verification", "root_group_protection", "root_values", "show_private_repo_watermark", "values"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DtoOrganizationSettingWithParent from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DtoOrganizationSettingWithParent from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "can_show_members": obj.get("can_show_members"),
            "can_show_sub_groups": obj.get("can_show_sub_groups"),
            "can_show_watermark": obj.get("can_show_watermark"),
            "email_verification": obj.get("email_verification"),
            "group_protection": obj.get("group_protection"),
            "hide_members": obj.get("hide_members"),
            "hide_sub_groups": obj.get("hide_sub_groups"),
            "root_email_verification": obj.get("root_email_verification"),
            "root_group_protection": obj.get("root_group_protection"),
            "root_values": obj.get("root_values"),
            "show_private_repo_watermark": obj.get("show_private_repo_watermark"),
            "values": obj.get("values")
        })
        return _obj


