# coding: utf-8

"""
    CNB OPENAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Contact: cnb@tencent.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class OrganizationSettingValue(int, Enum):
    """
    OrganizationSettingValue
    """

    """
    allowed enum values
    """
    DisableOrganizationReadme = 1
    CloudNativeDevOnly = 2
    UseRootGroupBranchProtectionOnly = 4
    ForbidRedefineBranchProtection = 8
    EnableTAPDAccess = 16

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of OrganizationSettingValue from a JSON string"""
        return cls(json.loads(json_str))


