# Generated by Django 4.2.20 on 2025-04-20 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_usersettings_is_2fa_enabled_and_more'),
        ('referrals', '0004_alter_referralreward_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acquisitionrecord',
            name='assigned_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_acquisitions', to='users.crmuser'),
        ),
        migrations.AlterField(
            model_name='referralsource',
            name='crm_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referral_codes', to='users.crmuser'),
        ),
        migrations.AlterField(
            model_name='rewarddistribution',
            name='recipient_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referral_rewards', to='users.crmuser'),
        ),
    ]
