# Generated by Django 4.2.19 on 2025-03-14 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ib_commission', '0008_commissiondistribution_is_processed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commissiondistribution',
            name='processing_notes',
            field=models.TextField(blank=True, help_text='Additional notes about processing status', null=True),
        ),
        migrations.AddField(
            model_name='commissiondistribution',
            name='processing_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSED', 'Processed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', help_text='Current status of the distribution processing', max_length=20),
        ),
        migrations.AddIndex(
            model_name='commissiondistribution',
            index=models.Index(fields=['processing_status'], name='commission__process_7f8018_idx'),
        ),
    ]
