# Generated by Django 4.2.19 on 2025-03-16 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ib_commission', '0011_commissiondistribution_rule'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='commissiondistribution',
            name='unique_distribution_per_ib',
        ),
        migrations.AddConstraint(
            model_name='commissiondistribution',
            constraint=models.UniqueConstraint(fields=('deal_ticket', 'customer', 'rule', 'is_pass_up'), name='unique_distribution_per_ib_rule_type'),
        ),
    ]
