# Generated by Django 3.2.25 on 2025-01-08 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nautobot_dns_records", "0003_constraints"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="srvrecord",
            constraint=models.UniqueConstraint(fields=("label", "target", "port"), name="srv_unique_label_target_port"),
        ),
        migrations.AddConstraint(
            model_name="sshfprecord",
            constraint=models.UniqueConstraint(fields=("label", "fingerprint"), name="sshfp_unique_label_fingerprint"),
        ),
    ]
