# coding: utf-8

"""
    OpenPay API

    super charge your subscription management.

    The version of the OpenAPI document: 1.2.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from typing import Any, Dict, Optional
from pydantic import BaseModel, Field, StrictBool, StrictStr
from getopenpay.models.object_name import ObjectName

class DisputeExternal(BaseModel):
    """
    DisputeExternal
    """
    account_id: StrictStr = Field(default=..., description="Unique identifier for the account.")
    created_at: datetime = Field(default=..., description="DateTime at which the object was created, in 'ISO 8601' format.")
    id: StrictStr = Field(default=..., description="Unique identifier of the dispute.")
    is_deleted: Optional[StrictBool] = Field(default=False, description="If true, indicates that this object has been deleted")
    metadata: Optional[Dict[str, Any]] = None
    object: Optional[ObjectName] = None
    payment_intent_id: StrictStr = Field(default=..., description="The payment intent id.")
    reason: Optional[StrictStr] = None
    their_dispute_id: StrictStr = Field(default=..., description="There dispute id.")
    their_payment_intent_id: StrictStr = Field(default=..., description="Their payment intent id")
    updated_at: datetime = Field(default=..., description="DateTime at which the object was updated, in 'ISO 8601' format.")
    __properties = ["account_id", "created_at", "id", "is_deleted", "metadata", "object", "payment_intent_id", "reason", "their_dispute_id", "their_payment_intent_id", "updated_at"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> DisputeExternal:
        """Create an instance of DisputeExternal from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # set to None if metadata (nullable) is None
        # and __fields_set__ contains the field
        if self.metadata is None and "metadata" in self.__fields_set__:
            _dict['metadata'] = None

        # set to None if reason (nullable) is None
        # and __fields_set__ contains the field
        if self.reason is None and "reason" in self.__fields_set__:
            _dict['reason'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> DisputeExternal:
        """Create an instance of DisputeExternal from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return DisputeExternal.parse_obj(obj)

        _obj = DisputeExternal.parse_obj({
            "account_id": obj.get("account_id"),
            "created_at": obj.get("created_at"),
            "id": obj.get("id"),
            "is_deleted": obj.get("is_deleted") if obj.get("is_deleted") is not None else False,
            "metadata": obj.get("metadata"),
            "object": obj.get("object"),
            "payment_intent_id": obj.get("payment_intent_id"),
            "reason": obj.get("reason"),
            "their_dispute_id": obj.get("their_dispute_id"),
            "their_payment_intent_id": obj.get("their_payment_intent_id"),
            "updated_at": obj.get("updated_at")
        })
        return _obj


