# coding: utf-8

"""
    OpenPay API

    super charge your subscription management.

    The version of the OpenAPI document: 1.2.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class PaymentIntentStatus(str, Enum):
    """
    PaymentIntentStatus
    """

    """
    allowed enum values
    """
    REQUIRES_CONFIRMATION = 'requires_confirmation'
    REQUIRES_CAPTURE = 'requires_capture'
    REQUIRES_ACTION = 'requires_action'
    REQUIRES_PAYMENT_METHOD = 'requires_payment_method'
    PROCESSING = 'processing'
    CANCELED = 'canceled'
    SUCCEEDED = 'succeeded'
    EXCEPTION = 'exception'

    @classmethod
    def from_json(cls, json_str: str) -> PaymentIntentStatus:
        """Create an instance of PaymentIntentStatus from a JSON string"""
        return PaymentIntentStatus(json.loads(json_str))


