from get_music.api import kugou
from get_music import download
from get_music.api import migu
from get_music.api import kuwo
from get_music.api import netease
from get_music.api import qq
from get_music.api import oneting
from get_music.api import fivesing
from get_music.api import baidu
