# Generated by Django 4.2.19 on 2025-03-04 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ib_commission', '0004_rename_ib_commissi_account_76e731_idx_ib_commissi_account_10d556_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ibagreementmember',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
