# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sapiopycommons/ai/api/plan/proto/step_output.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'sapiopycommons/ai/api/plan/proto/step_output.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n2sapiopycommons/ai/api/plan/proto/step_output.proto\"$\n\x13StepJsonOutputEntry\x12\r\n\x05\x65ntry\x18\x01 \x01(\t\"$\n\x13StepTextOutputEntry\x12\r\n\x05\x65ntry\x18\x01 \x01(\t\"#\n\x12StepCsvOutputEntry\x12\r\n\x05\x63\x65lls\x18\x01 \x03(\t\"&\n\x15StepBinaryOutputEntry\x12\r\n\x05\x65ntry\x18\x01 \x01(\x0c\"\xd1\x01\n\x0fStepOutputEntry\x12+\n\x0bjson_output\x18\x01 \x01(\x0b\x32\x14.StepJsonOutputEntryH\x00\x12+\n\x0btext_output\x18\x02 \x01(\x0b\x32\x14.StepTextOutputEntryH\x00\x12)\n\ncsv_output\x18\x03 \x01(\x0b\x32\x13.StepCsvOutputEntryH\x00\x12/\n\rbinary_output\x18\x04 \x01(\x0b\x32\x16.StepBinaryOutputEntryH\x00\x42\x08\n\x06outputB\x1c\n\x18\x63om.velox.api.plan.protoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sapiopycommons.ai.api.plan.proto.step_output_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\030com.velox.api.plan.protoP\001'
  _globals['_STEPJSONOUTPUTENTRY']._serialized_start=54
  _globals['_STEPJSONOUTPUTENTRY']._serialized_end=90
  _globals['_STEPTEXTOUTPUTENTRY']._serialized_start=92
  _globals['_STEPTEXTOUTPUTENTRY']._serialized_end=128
  _globals['_STEPCSVOUTPUTENTRY']._serialized_start=130
  _globals['_STEPCSVOUTPUTENTRY']._serialized_end=165
  _globals['_STEPBINARYOUTPUTENTRY']._serialized_start=167
  _globals['_STEPBINARYOUTPUTENTRY']._serialized_end=205
  _globals['_STEPOUTPUTENTRY']._serialized_start=208
  _globals['_STEPOUTPUTENTRY']._serialized_end=417
# @@protoc_insertion_point(module_scope)
